/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WaitingForApprovalRouteImport } from './routes/waiting-for-approval'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminActivationCodesRouteImport } from './routes/_admin.admin.activation-codes'
import { Route as AdminAdminAiImportRouteImport } from './routes/_admin.admin.ai-import'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin.analytics'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin.admin.audit'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin.admin.courses'
import { Route as AdminAdminExamsRouteImport } from './routes/_admin.admin.exams'
import { Route as AdminAdminQuestionsRouteImport } from './routes/_admin.admin.questions'
import { Route as AdminAdminRankingsRouteImport } from './routes/_admin.admin.rankings'
import { Route as AdminAdminResultsRouteImport } from './routes/_admin.admin.results'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin.admin.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingForApprovalRoute = WaitingForApprovalRouteImport.update({
  id: '/waiting-for-approval',
  path: '/waiting-for-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminActivationCodesRoute =
  AdminAdminActivationCodesRouteImport.update({
    id: '/activation-codes',
    path: '/activation-codes',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminAiImportRoute = AdminAdminAiImportRouteImport.update({
  id: '/ai-import',
  path: '/ai-import',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminExamsRoute = AdminAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminQuestionsRoute = AdminAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRankingsRoute = AdminAdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminResultsRoute = AdminAdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/waiting-for-approval': typeof WaitingForApprovalRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/admin/activation-codes': typeof AdminAdminActivationCodesRoute
  '/admin/ai-import': typeof AdminAdminAiImportRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/exams': typeof AdminAdminExamsRoute
  '/admin/questions': typeof AdminAdminQuestionsRoute
  '/admin/rankings': typeof AdminAdminRankingsRoute
  '/admin/results': typeof AdminAdminResultsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/waiting-for-approval': typeof WaitingForApprovalRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/admin/activation-codes': typeof AdminAdminActivationCodesRoute
  '/admin/ai-import': typeof AdminAdminAiImportRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/exams': typeof AdminAdminExamsRoute
  '/admin/questions': typeof AdminAdminQuestionsRoute
  '/admin/rankings': typeof AdminAdminRankingsRoute
  '/admin/results': typeof AdminAdminResultsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/waiting-for-approval': typeof WaitingForApprovalRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/_admin/admin/activation-codes': typeof AdminAdminActivationCodesRoute
  '/_admin/admin/ai-import': typeof AdminAdminAiImportRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRoute
  '/_admin/admin/exams': typeof AdminAdminExamsRoute
  '/_admin/admin/questions': typeof AdminAdminQuestionsRoute
  '/_admin/admin/rankings': typeof AdminAdminRankingsRoute
  '/_admin/admin/results': typeof AdminAdminResultsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activate'
    | '/auth'
    | '/waiting-for-approval'
    | '/admin'
    | '/dashboard'
    | '/exam/$examId'
    | '/result/$attemptId'
    | '/admin/activation-codes'
    | '/admin/ai-import'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/questions'
    | '/admin/rankings'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activate'
    | '/auth'
    | '/waiting-for-approval'
    | '/dashboard'
    | '/exam/$examId'
    | '/result/$attemptId'
    | '/admin/activation-codes'
    | '/admin/ai-import'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/questions'
    | '/admin/rankings'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authed'
    | '/about'
    | '/activate'
    | '/auth'
    | '/waiting-for-approval'
    | '/_admin/admin'
    | '/_authed/dashboard'
    | '/exam/$examId'
    | '/result/$attemptId'
    | '/_admin/admin/activation-codes'
    | '/_admin/admin/ai-import'
    | '/_admin/admin/analytics'
    | '/_admin/admin/audit'
    | '/_admin/admin/courses'
    | '/_admin/admin/exams'
    | '/_admin/admin/questions'
    | '/_admin/admin/rankings'
    | '/_admin/admin/results'
    | '/_admin/admin/settings'
    | '/_admin/admin/students'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  WaitingForApprovalRoute: typeof WaitingForApprovalRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-for-approval': {
      id: '/waiting-for-approval'
      path: '/waiting-for-approval'
      fullPath: '/waiting-for-approval'
      preLoaderRoute: typeof WaitingForApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/activation-codes': {
      id: '/_admin/admin/activation-codes'
      path: '/activation-codes'
      fullPath: '/admin/activation-codes'
      preLoaderRoute: typeof AdminAdminActivationCodesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ai-import': {
      id: '/_admin/admin/ai-import'
      path: '/ai-import'
      fullPath: '/admin/ai-import'
      preLoaderRoute: typeof AdminAdminAiImportRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/exams': {
      id: '/_admin/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminAdminExamsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/questions': {
      id: '/_admin/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminAdminQuestionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/rankings': {
      id: '/_admin/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminAdminRankingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/results': {
      id: '/_admin/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminAdminResultsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminActivationCodesRoute: typeof AdminAdminActivationCodesRoute
  AdminAdminAiImportRoute: typeof AdminAdminAiImportRoute
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRoute
  AdminAdminExamsRoute: typeof AdminAdminExamsRoute
  AdminAdminQuestionsRoute: typeof AdminAdminQuestionsRoute
  AdminAdminRankingsRoute: typeof AdminAdminRankingsRoute
  AdminAdminResultsRoute: typeof AdminAdminResultsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminActivationCodesRoute: AdminAdminActivationCodesRoute,
  AdminAdminAiImportRoute: AdminAdminAiImportRoute,
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminCoursesRoute: AdminAdminCoursesRoute,
  AdminAdminExamsRoute: AdminAdminExamsRoute,
  AdminAdminQuestionsRoute: AdminAdminQuestionsRoute,
  AdminAdminRankingsRoute: AdminAdminRankingsRoute,
  AdminAdminResultsRoute: AdminAdminResultsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  WaitingForApprovalRoute: WaitingForApprovalRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
